"""
SQLAlchemy models for AI IT Operations.

Every table carries customer_id from day one, even though the MVP
only ever has a single hardcoded synthetic customer. Retrofitting a
tenant column onto every query later is expensive; adding it now
while there's one row costs nothing. This is "designing for
multi-tenancy without building it" per the original architecture.

This database is local, file-based (SQLite), and never contains real
company data — only synthetic records generated by
data/generate_synthetic_data.py.
"""

from datetime import datetime

from sqlalchemy import (
    JSON,
    Column,
    DateTime,
    Float,
    ForeignKey,
    Integer,
    String,
    create_engine,
)
from sqlalchemy.orm import DeclarativeBase, Session, relationship


class Base(DeclarativeBase):
    pass


class Customer(Base):
    __tablename__ = "customers"

    id = Column(Integer, primary_key=True)
    name = Column(String, nullable=False)
    created_at = Column(DateTime, default=datetime.utcnow)


class Ticket(Base):
    __tablename__ = "tickets"

    id = Column(Integer, primary_key=True)
    customer_id = Column(Integer, ForeignKey("customers.id"), nullable=False)
    external_id = Column(String, nullable=False)
    source_system = Column(String, nullable=False)
    title = Column(String)
    category = Column(String)
    priority = Column(String)
    status = Column(String)
    opened_at = Column(DateTime, nullable=False)
    closed_at = Column(DateTime, nullable=True)
    sla_target_hours = Column(Float)
    assigned_to = Column(String)
    vendor = Column(String, nullable=True)


class NetworkSample(Base):
    __tablename__ = "network_samples"

    id = Column(Integer, primary_key=True)
    customer_id = Column(Integer, ForeignKey("customers.id"), nullable=False)
    site = Column(String, nullable=False)
    sample_date = Column(DateTime, nullable=False)
    bandwidth_mbps_committed = Column(Float)
    bandwidth_mbps_measured = Column(Float)
    latency_ms = Column(Float)
    packet_loss_pct = Column(Float)
    uptime_pct = Column(Float)
    circuit_provider = Column(String, nullable=True)


class KPISnapshot(Base):
    __tablename__ = "kpi_snapshots"

    id = Column(Integer, primary_key=True)
    customer_id = Column(Integer, ForeignKey("customers.id"), nullable=False)
    period_label = Column(String, nullable=False)
    ticket_kpis = Column(JSON)
    network_kpis = Column(JSON)
    cost_kpis = Column(JSON)
    recurring_categories = Column(JSON)
    computed_at = Column(DateTime, default=datetime.utcnow)


class Report(Base):
    __tablename__ = "reports"

    id = Column(Integer, primary_key=True)
    customer_id = Column(Integer, ForeignKey("customers.id"), nullable=False)
    period_label = Column(String, nullable=False)
    ai_report_json = Column(JSON)
    pdf_path = Column(String, nullable=True)
    excel_path = Column(String, nullable=True)
    generated_at = Column(DateTime, default=datetime.utcnow)

    kpi_snapshot_id = Column(Integer, ForeignKey("kpi_snapshots.id"), nullable=True)
    kpi_snapshot = relationship("KPISnapshot")


# Stubs for future phases — defined now so the model doesn't need
# rework later, unused by MVP code paths.
class Vendor(Base):
    __tablename__ = "vendors"

    id = Column(Integer, primary_key=True)
    customer_id = Column(Integer, ForeignKey("customers.id"), nullable=False)
    name = Column(String, nullable=False)


class Contract(Base):
    __tablename__ = "contracts"

    id = Column(Integer, primary_key=True)
    customer_id = Column(Integer, ForeignKey("customers.id"), nullable=False)
    vendor_id = Column(Integer, ForeignKey("vendors.id"), nullable=True)
    vendor_name = Column(String, nullable=True)
    service_name = Column(String)
    annual_cost = Column(Float, nullable=True)
    renewal_date = Column(DateTime, nullable=True)
    license_count = Column(Integer, nullable=True)
    licenses_in_use = Column(Integer, nullable=True)


class SecurityEvent(Base):
    __tablename__ = "security_events"

    id = Column(Integer, primary_key=True)
    customer_id = Column(Integer, ForeignKey("customers.id"), nullable=False)
    source_system = Column(String)
    severity = Column(String)
    event_type = Column(String)
    occurred_at = Column(DateTime, nullable=True)


def get_engine(db_path: str = "sqlite:///ai_it_operations.db"):
    return create_engine(db_path)


def init_db(engine) -> None:
    Base.metadata.create_all(engine)


def get_session(engine) -> Session:
    return Session(engine)
